### ISSUE TITLE
problem getting inverters from different bus

### ISSUE THREAD

**Issue by edelsau-coder** [iobroker-community-adapters/ioBroker.solarlog#38]
Hi there,

I use a Solar Log Base with inverters on RS485A and on RS485B.

![image](https://user-images.githubusercontent.com/76178177/105019824-d43e5f00-5a46-11eb-848e-c507039ec797.png)

Unfortunately the inverters are not displayed correctly.

![image](https://user-images.githubusercontent.com/76178177/105020063-1ebfdb80-5a47-11eb-9fb0-93368c26b4eb.png)

Inverter1 has display problems. I'll try to reload it to solve it. No folder is shown.

Inverter2 is the Kaco of the RS485B bus.
Therefore Inverter2 is missing from the RS485A bus.

Maybe there is a possibility to address the inverter numbers differently.

Many thanks!

**Comment by forelleblau** [comment]
Hi
I hope the reload brougt the details for Inverter 1 / WR 1

Since the adapter reads the names of the inverters/devices in the solarlog and sets up the channels/objects according to this names, the easiest way for your problem with WR 2 (ok, my point of view) would be to rename the KACO - WR 2 (see configuration tab in your screenshot). As an alternative i could offer to optionally create/name the channel/object - with a combination of inverter/device name and number (i.e. 8:WR2).

**Comment by edelsau-coder** [comment]
Hi there,

Yes. i think everything has been resolved and we can close the case here.

1. reloading with historical values ​​up to an hour worked great.

2. Renaming the inverter in the solarlog interface was also successful.

Thank you for support!

**Comment by forelleblau** [comment]
Tx 4 feedback
